apiVersion: v2
name: brigade
description: |
  A Helm chart for Brigade
type: application
version: v0.0.0
appVersion: v0.0.0
sources:
- https://github.com/brigadecore/brigade
maintainers:
- name: Kent Rancourt
  email: kent.rancourt@gmail.com
dependencies:
- name: mongodb
  version: 10.3.7
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
